name: Client Pipeline

on:
  pull_request:
    branches:
      - 'main'
      - 'develop'
    paths:
      - 'client/**.js'
      - 'client/package*.json'
      - 'docker/dockerfiles/Dockerfile.frontend*'
      - 'docker-compose.yml'
      - '.github/workflows/client_pipeline.yml'

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-22.04
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Node.js dependencies
      run: npm install
      working-directory: client/

    - name: Run linters
      run: npm run lint
      working-directory: client/

  tests:
    name: Run client tests
    runs-on: ubuntu-22.04
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Node.js dependencies
      run: npm install
      working-directory: client/

    - name: Build app
      run: npm run build --if-present
      working-directory: client/

    - name: Run tests
      run: npm test
      working-directory: client/
