name: Run first-time set-up for MacOS and Linux

on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:
    branches:
      - 'main'
      - 'develop'
    paths:
      - 'api/**'
      - 'client/**'
      - '.github/workflows/*'
      - './docker-compose.yml'

jobs:
  ubuntu-set-up:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set-up Docker
      run: |
        make install-docker-ubuntu
    - name: Create envirnoment file
      run: |
        cp .env.dev .env
    - name: Initialize environment
      run: |
        make build
